[project]
name = "crypto-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.43",
    "pandas>=2.3.3",
    "pycoingecko>=3.2.0",
    "python-dotenv>=1.1.1",
]
